apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-one
  namespace: ernest-kim
  labels:
    app: project-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-one
  template:
    metadata:
      labels:
        app: project-one
    spec:
      volumes:
      - name: config
        configMap:
          name: fluent-conf
      containers:
      - name: fluentd
        image: grafana/fluent-plugin-loki:latest
        ports:
        - containerPort: 24224
        env:
        - name: LOKI_URL
          value: "http://loki:3100"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
      - name: project-one
        image: ernestk86/project-one:0.0.7
        ports:
        - containerPort: 8880
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: project-one-credentials
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: project-one-credentials
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-one-credentials
              key: DB_PASSWORD
        - name: AWS_SES_HOST
          valueFrom:
            secretKeyRef:
              name: project-one-credentials
              key: AWS_SES_HOST
        - name: AWS_SES_USERNAME
          valueFrom:
            secretKeyRef:
              name: project-one-credentials
              key: AWS_SES_USERNAME
        - name: AWS_SES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-one-credentials
              key: AWS_SES_PASSWORD
