apiVersion: v1
kind: Pod
metadata:
  name: project-one-pod
  labels:
    app: project-one
spec:
  containers:
  - name: project-one
    image: project-one-local:latest
    ports:
    - containerPort: 8880
    imagePullPolicy: Never
    envFrom:
    - secretRef:
      name: ernest-kim-secret
  containers:
  - name: fluentd
    image: fluentd:latest
    ports:
    - containerPort: 24224
    env:
    - name: LOKI_URL
      value: "http://loki:3100"
    imagePullPolicy: Never