-- DROP SCHEMA rentals_vg;

CREATE SCHEMA rentals_vg;

-- rentals_vg.games definition

-- Drop table

-- DROP TABLE rentals_vg.games;

CREATE TABLE rentals_vg.games (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	available bool NULL DEFAULT true,
	avg_rating numeric NULL DEFAULT 0.0,
	console varchar(255) NOT NULL,
	date_released date NULL,
	developer varchar(255) NULL,
	genre varchar(255) NOT NULL,
	multiplayer bool NULL DEFAULT false,
	"name" varchar(255) NOT NULL,
	publisher varchar(255) NULL,
	CONSTRAINT games_pkey PRIMARY KEY (id)
);


-- rentals_vg.users definition

-- Drop table

-- DROP TABLE rentals_vg.users;

CREATE TABLE rentals_vg.users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address varchar(255) NOT NULL,
	city varchar(255) NOT NULL,
	date_of_birth date NOT NULL,
	"password" varchar(255) NOT NULL,
	state varchar(255) NOT NULL,
	username varchar(255) NOT NULL,
	zip_code int4 NOT NULL,
	"role" varchar(255) NOT NULL DEFAULT 'CUSTOMER'::character varying,
	CONSTRAINT uk_r43af9ap4edm43mmtq01oddj6 UNIQUE (username),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_zip_code_check CHECK (((zip_code >= 1000) AND (zip_code <= 99999)))
);


-- rentals_vg.rentals definition

-- Drop table

-- DROP TABLE rentals_vg.rentals;

CREATE TABLE rentals_vg.rentals (
	game_id int4 NOT NULL,
	due_date date NOT NULL DEFAULT CURRENT_DATE + 14,
	over_due bool NULL DEFAULT false,
	user_id int4 NOT NULL,
	CONSTRAINT rentals_pkey PRIMARY KEY (game_id),
	CONSTRAINT fkld66vyqacyd8lwn3fm0qwvvyr FOREIGN KEY (game_id) REFERENCES rentals_vg.games(id),
	CONSTRAINT fktnhd1objf2mlb6ag6k726u269 FOREIGN KEY (user_id) REFERENCES rentals_vg.users(id)
);


-- rentals_vg.reviews definition

-- Drop table

-- DROP TABLE rentals_vg.reviews;

CREATE TABLE rentals_vg.reviews (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	rating int4 NOT NULL,
	written_review varchar(255) NOT NULL,
	game_id int4 NULL,
	CONSTRAINT reviews_pkey PRIMARY KEY (id),
	CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 10))),
	CONSTRAINT fk1cmcqkmc8g630wpn52m1mv8re FOREIGN KEY (game_id) REFERENCES rentals_vg.games(id)
);

-- DROP TYPE rentals_vg.consoles;

CREATE TYPE rentals_vg.consoles AS ENUM (
	'NES',
	'SNES',
	'N64',
	'GAMECUBE',
	'WII',
	'WIIU',
	'SWITCH',
	'GAMEBOY',
	'GBA',
	'NDS',
	'N3DS',
	'MASTERSYSTEM',
	'GENESIS',
	'SEGACD',
	'SATURN',
	'DREAMCAST',
	'GAMEGEAR',
	'ATARI2600',
	'JAGUAR',
	'PSX',
	'PS2',
	'PS3',
	'PS4',
	'PS5',
	'PSP',
	'PSVita',
	'XBOX',
	'XBOX360',
	'XBOXONE',
	'XBOXSERIES',
	'PC');

-- DROP TYPE rentals_vg.genre;

CREATE TYPE rentals_vg.genre AS ENUM (
	'ACTION_ADVENTURE',
	'ROLE_PLAYING',
	'STRATEGY',
	'FIRST_PERSON_SHOOTER',
	'VISUAL_NOVEL',
	'SPORTS',
	'SIMULATION',
	'PUZZLE',
	'PARTY',
	'HORROR',
	'MOBA',
	'RHYTHM',
	'BATTLE_ROYALE',
	'FIGHTING');

-- DROP TYPE rentals_vg.roles;

CREATE TYPE rentals_vg.roles AS ENUM (
	'ADMIN',
	'CUSTOMER');

-- DROP TYPE rentals_vg.states;

CREATE TYPE rentals_vg.states AS ENUM (
	'AL',
	'AK',
	'AZ',
	'AR',
	'CA',
	'CO',
	'CT',
	'DE',
	'FL',
	'GA',
	'HI',
	'ID',
	'IL',
	'IN',
	'IA',
	'KS',
	'KY',
	'LA',
	'ME',
	'MD',
	'MA',
	'MI',
	'MN',
	'MS',
	'MO',
	'MT',
	'NE',
	'NV',
	'NH',
	'NJ',
	'NM',
	'NY',
	'NC',
	'ND',
	'OH',
	'OK',
	'OR',
	'PA',
	'RI',
	'SC',
	'SD',
	'TN',
	'TX',
	'UT',
	'VT',
	'VA',
	'WA',
	'WV',
	'WI',
	'WY');
